version: "3.7"
services:
    kafka:
        image: 'bitnami/kafka:latest'
        container_name: kafka
        #    volumes:
        #      - ./logs/kafka:/bitnami/kafka
        ports:
            - '9092:9092'
        environment:
            KAFKA_ENABLE_KRAFT: yes
            KAFKA_BROKER_ID: 1
            KAFKA_CFG_NODE_ID: 1
            ALLOW_PLAINTEXT_LISTENER: yes
            KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@127.0.0.1:9093
            KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
            KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_CFG_PROCESS_ROLES: controller,broker
            KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
            KAFKA_CFG_LISTENERS: PLAINTEXT://:29092,PLAINTEXT_HOST://0.0.0.0:9092,CONTROLLER://:9093
            KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
    jobmanager:
        build: .
        container_name: jobmanager
        ports:
            - "8081:8081"
        command: jobmanager
        volumes:
            - ./jars/:/opt/flink/jars
            - ./logs/flink/jm:/opt/flink/temp
            - ./schema/:/opt/flink/schema
        environment:
            - |
                FLINK_PROPERTIES=
                jobmanager.rpc.address: jobmanager
    taskmanager1:
        build: .
        container_name: taskmanager1
        depends_on:
            - jobmanager
        command: taskmanager
        volumes:
            - ./logs/flink/tm1:/opt/flink/temp
            - ./flink/filer:/opt/flink/filer
            - ./schema/:/opt/flink/schema
        environment:
            - |
                FLINK_PROPERTIES=
                jobmanager.rpc.address: jobmanager
                taskmanager.numberOfTaskSlots: 2
    taskmanager2:
        build: .
        container_name: taskmanager2
        depends_on:
            - jobmanager
        command: taskmanager
        volumes:
            - ./logs/flink/tm2:/opt/flink/temp
            - ./flink/filer:/opt/flink/filer
            - ./schema/:/opt/flink/schema
        environment:
            - |
                FLINK_PROPERTIES=
                jobmanager.rpc.address: jobmanager
                taskmanager.numberOfTaskSlots: 2
    postgres:
        image: postgres:latest
        container_name: postgres
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - '5432:5432'